[tool.poetry]
name = "jsonschema-instance"
version = "0.1.0"
description = ""
authors = ["Martin Boos <mboos@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.7"
exrex = "^0.10.5"

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
